<?php
$tagline="Possibilities beyond cargo.";
$home_banner_image1=get_bloginfo('template_url').'/images/banner1.jpg';
$home_banner_image2=get_bloginfo('template_url').'/images/banner2.jpg';
$home_banner_image3=get_bloginfo('template_url').'/images/banner3.jpg';
$lp_about_heading="About Hong Tah Logistics Inc.";
$lp_about_btn="Learn More";
$lp_about_text="Hong Tah Logistics Inc. is a privately owned trucking company that renders land transportation needs of customers and suppliers from the origin point to destination point. It seeks to accrue impressive customer and vendor rating by providing a respectable level of service integrity to its business partners.";
$lp_about_btnurl=get_site_url().'/about-us';
$lp_services_bgimage=get_bloginfo('template_url').'/images/services-bg.jpg';
$lp_services_heading="Services";
$lp_service1_text="Hong Tah Logistics Inc․, is a trucking service company engaged in hauling and delivering general cargos through prime trucks.";
$lp_service1_btn="Go to Services";
$lp_service1_url=get_site_url().'/services';
$lp_service2_text="HTLI offers short-term and long-term warehousing services, prioritizing the security of the items.";
$lp_service2_btn="Go to Services";
$lp_service2_url= get_site_url().'/services';
$service_banner_heading="What we do";
$service_banner_text="Hong Tah Logistics Inc., provides trucking services to companies demanding goods-forwarding services.";
$service_banner_image=get_bloginfo('template_directory').'/images/banner3.jpg';
$service1_bgimage=get_bloginfo('template_url').'/images/banner1.jpg';
$service2_bgimage=get_bloginfo('template_url').'/images/banner3.jpg';
$service1_heading="Trucking";
$service2_heading="Warehouse Storage Solutions";
$service1_content="Hong Tah Logistics Inc&#8228;, is a trucking service company engaged in hauling and delivering general cargos through prime trucks. Setting reliable standards for reasonable-cost cargo moving in Metro Manila trips. We believe in being diligent and fast in every transaction with our clients, giving full safety and priority to customer’s goods. Our professional employees make sure that the client’s items get moved safely and securely.";
$service2_content="HTLI offers short-term and long-term warehousing services, prioritizing the security of the items. We also offer last-minute storage solutions without compromising the condition and qualities of the goods. Our quality service are made sure to meet your supply-chain processs and standards as easily and fast as possible.";
$contact_banner_heading="Contact Us";
$contact_banner_text="";
$contact_banner_image=get_bloginfo('template_url').'/images/services-bg.jpg';
$email_heading="Email";
$phone_heading="Phone";
$email="hongtahlogistics@gmail.com";
$phone="+63 2 952-5134";
$loc1_heading="Main Location";
$loc2_heading="Parking Location";
$loc1_content="Polylite Industrial Corp., Alabang–Zapote Road, Talon, Las Pinas, 1740 Metro Manila";
$loc2_content="Polylite Industrial Corp., Alabang–Zapote Road, Talon, Las Pinas, 1740 Metro Manila";
$loc1_url="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d15458.997220850415!2d120.9776426!3d14.3839114!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xcf4d2b72b0b2735c!2sSM+Molino!5e0!3m2!1sfil!2sph!4v1547304953066";
$loc2_url="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d15458.997220850415!2d120.9776426!3d14.3839114!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xcf4d2b72b0b2735c!2sSM+Molino!5e0!3m2!1sfil!2sph!4v1547304953066";
$about_banner_heading="Company Profile";
$about_text="Hong Tah Logistics Inc. is a privately owned trucking company that renders land transportation needs of customers and suppliers from the origin point to destination point. It seeks to accrue impressive customer and vendor rating by providing a respectable level of service integrity to its business partners.";
$about_banner_image=get_bloginfo('template_directory').'/images/services-bg.jpg';
$vision="Vision";
$vision_content="A developing and expanding logistics business through reliable, and insightful trucking and transportation services.";
$mission="Mission";
$mission_content="To be a reputable and proved trucking service provider in the Philippines.";
$client_promise="Client Promise";
$client_promise_content="We culture time, effort and fund efficiency in all parts of our operations. ";
/* function first_sentence($content) {
    $pos = strpos($content, '.');
    return substr($content, 0, $pos+1); 
} */